### ISSUE TITLE
Wrong usage of MSG_NOSIGNAL on Linux

### ISSUE THREAD

**Issue by Hadatko** [awslabs/aws-c-io#303]
Hello, 
i am trying to debug your socket implementation as it looks that there can be issue. First small one i found looks usage of MSG_NOSIGNAL.
Everywhere on internet i see this recomandation:
```
Code for OS X:

setsockopt(sd, SOL_SOCKET, SO_NOSIGPIPE, ...)

Code for Linux (2.2+):

send(..., MSG_NOSIGNAL)
```

Your usage:
```
define NO_SIGNAL MSG_NOSIGNAL
if (AWS_UNLIKELY(
            setsockopt(socket->io_handle.data.fd, SOL_SOCKET, NO_SIGNAL, &option_value, sizeof(option_value)))) {
        AWS_LOGF_WARN(
            AWS_LS_IO_SOCKET,
            "id=%p fd=%d: setsockopt() for NO_SIGNAL failed with errno %d. If you are having SIGPIPE signals thrown, "
            "you may"
            " want to install a signal trap in your application layer.",
            (void *)socket,
            socket->io_handle.data.fd,
            errno);
    }
```
This looks like it should always return warning on Linux systems...
Here is descrition for send and MSG_NOSIGNAL definition: https://linux.die.net/man/2/send
Here setsockopt definition with missing MSG_NOSIGNAL definition: https://linux.die.net/man/3/setsockopt

**Comment by Hadatko** [comment]
It looks like there are more options on Linux to use:
https://stackoverflow.com/questions/26752649/so-nosigpipe-was-not-decleared

**Comment by kankri** [comment]
We are seeing this as well and it's causing us some trouble. Here's an example log:
```
DEBUG: task-scheduler: id=0x7f3434004010: Running attempt_connection task with <Running> status
DEBUG: socket: id=0x7f343c000b90 fd=9: initializing with domain 1 and type 0
DEBUG: socket: id=0x7f343c000b90 fd=9: setting socket options to: keep-alive 0, keep idle 0, keep-alive interval 0, keep-alive probe count 0.
WARN : socket: id=0x7f343c000b90 fd=9: setsockopt() for NO_SIGNAL failed with errno 92. If you are having SIGPIPE signals thrown, you may want to install a signal trap in your application layer.
DEBUG: socket: id=0x7f343c000b90 fd=9: beginning connect.
```
This error 92 ([ENOPROTOOPT](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/asm-generic/errno.h#n75), Protocol not available) is indeed caused because you [currently](https://github.com/awslabs/aws-c-io/tree/abb87bc21509283b8f7b42b664741a8d5637985a) in `main` are doing [this](https://github.com/awslabs/aws-c-io/blob/abb87bc21509283b8f7b42b664741a8d5637985a/source/posix/socket.c#L29):
```c
#if defined(__MACH__)
#    define NO_SIGNAL SO_NOSIGPIPE
#    define TCP_KEEPIDLE TCP_KEEPALIVE
#else
#    define NO_SIGNAL MSG_NOSIGNAL
#endif
```
and [this](https://github.com/awslabs/aws-c-io/blob/abb87bc21509283b8f7b42b664741a8d5637985a/source/posix/socket.c#L1163):
```c
            setsockopt(socket->io_handle.data.fd, SOL_SOCKET, NO_SIGNAL, &option_value, sizeof(option_value)))) {
```
Passing `MSG_*` options intended for `send(2)` and `recv(2)` to `setsockopt()` expecting `SO_*` options is incorrect. Luckily the value of `MSG_NOSIGNAL` is not a valid `setsockopt()` option, otherwise this call might be doing something totally unrelated.

Indeed the correct way to avoid `SIGPIPE` in Linux is to use `send()` with the [`MSG_NOSIGNAL` option](https://man7.org/linux/man-pages/man2/send.2.html):
```
       MSG_NOSIGNAL (since Linux 2.2)
              Don't generate a SIGPIPE signal if the peer on a stream-
              oriented socket has closed the connection.  The EPIPE
              error is still returned.  This provides similar behavior
              to using sigaction(2) to ignore SIGPIPE, but, whereas
              MSG_NOSIGNAL is a per-call feature, ignoring SIGPIPE sets
              a process attribute that affects all threads in the
              process.
```
This description also nicely highlights the problem of the suggestion "you may want to install a signal trap in your application layer" in the error message: by default SIGPIPE is not ignored which causes process termination and ignoring it affects the whole process. When I'm creating a library which uses `aws-c-io` I can't use `sigaction(2)` in my library. Maybe the final application also doesn't want to use it because it doesn't want to ignore all SIGPIPE signals from all sources, or wants to process those signals in a special way (exit cleanly when a SIGPIPE is received in a shell pipeline).

So like @Hadatko correctly pointed out over a year ago, the SDK is currently not doing socket handling the correct way on the Linux platform and this has undesired effects. Can you please fix this?

**Comment by bretambrose** [comment]
This should now be fixed.
